version: '3.8'

services:
  civic-db:
    networks:
      - civic-hub
    image: postgres:13
    restart: always
    container_name: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
    ports:
      - '5432:5432'
    volumes:
      - postgres:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    networks:
      - civic-hub
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=root@admin.com
      - PGADMIN_DEFAULT_PASSWORD=password
    ports:
      - "5050:80"
    depends_on:
      - civic-db

  nuxt-app:
    networks:
      - civic-hub
    container_name: nuxt-app
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
      - POSTGRES_DB=civic-db
      - DB_USER_NAME=civic-dba
      - POSTGRES_PASSWORD=password
      - DB_HOST=postgres
      - DB_NAME=postgres
    depends_on:
      - civic-db
    ports:
      - "3000:3000"

volumes:
  postgres:
    name: postgres-db

networks:
  civic-hub:
